import {
  Course,
  StepDefinition,
  SapCourseStepDefinition,
  FeedbackRecord,
  StepDropOffStat,
  StepRatingStat,
  AITheme,
  DashboardInsights,
  IdeaCard,
} from '../types';

/* =====================================================================
 * 1. EXISTING PURCHASE ORDER GUIDED PRACTICE STEPS — UNTOUCHED & KEPT
 * ===================================================================== */
export const PRACTICE_STEPS: StepDefinition[] = [
  {
    id: 1,
    stepNumber: 1,
    title: 'Select Supplier',
    instruction: 'Select an authorized vendor from the Supplier lookup list to begin the purchase order.',
    detailedHelp: 'Click on the "Supplier" selection field and choose one of the approved regional vendors.',
    hint: 'Open the Supplier field and select the required supplier from the dropdown menu.',
    fieldLabel: 'Vendor / Supplier Name',
    targetFieldId: 'po-supplier-select',
  },
  {
    id: 2,
    stepNumber: 2,
    title: 'Select Product',
    instruction: 'Choose the catalog item for this order requisition from the Product dropdown.',
    detailedHelp: 'Select the primary inventory item needed for the department replenishment.',
    hint: 'Choose a product from the Product dropdown list.',
    fieldLabel: 'Catalog Product Item',
    targetFieldId: 'po-product-select',
  },
  {
    id: 3,
    stepNumber: 3,
    title: 'Enter Quantity',
    instruction: 'Specify the required quantity of units for the chosen procurement item.',
    detailedHelp: 'Enter the exact positive integer quantity to order. Must be at least 1 unit.',
    hint: 'Enter the required quantity in the Quantity field. The value must be greater than 0.',
    fieldLabel: 'Order Quantity (Units)',
    targetFieldId: 'po-quantity-input',
  },
  {
    id: 4,
    stepNumber: 4,
    title: 'Submit Purchase Order',
    instruction: 'Review the purchase order summary carefully and submit the order for approval.',
    detailedHelp: 'Check supplier, line item, and unit quantity, then click the Submit Order button.',
    hint: 'Review your purchase order details carefully, then select the Submit Order button.',
    fieldLabel: 'Final Review & Dispatch',
    targetFieldId: 'po-submit-button',
  },
];

/* =====================================================================
 * 2. NEW SAP FUNDAMENTALS COURSE GUIDE STEPS — SEPARATE LEARNING FLOW
 * ===================================================================== */
export const SAP_COURSE_GUIDE_STEPS: SapCourseStepDefinition[] = [
  {
    id: 1,
    stepNumber: 1,
    title: 'Understand SAP Fundamentals',
    subtitle: 'Enterprise Systems & ERP Purpose',
    instruction: 'Review what SAP stands for, what an Enterprise Resource Planning (ERP) platform achieves, and why global organizations rely on integrated systems.',
    conceptSummary: 'SAP (Systeme, Anwendungen und Produkte in der Datenverarbeitung) is the market leader in enterprise software. ERP connects disparate departmental databases—such as accounting, warehousing, sales, and purchasing—into a unified real-time system.',
    hint: 'Start by reviewing what SAP is, what ERP means, and how SAP helps businesses manage their processes.',
    keyTakeaways: [
      'ERP breaks down departmental silos by sharing a single corporate database.',
      'SAP manages end-to-end business records with strict audit compliance.',
      'Real-time data synchronization avoids duplicate data entry across teams.',
    ],
    interactiveElement: {
      type: 'concept_cards',
      title: 'Explore ERP vs Traditional Siloed Software',
    },
  },
  {
    id: 2,
    stepNumber: 2,
    title: 'Explore Core SAP Concepts',
    subtitle: 'Master Data, Org Units & Transactions',
    instruction: 'Explore how SAP categorizes enterprise information into Organizational Units, Master Data (Vendor, Material), and Transactional Documents.',
    conceptSummary: 'Master data remains stable over long periods (e.g., Supplier address, Material specifications), whereas Transactional data represents specific business events (e.g., Purchase Order #9042 created on Sept 23).',
    hint: 'Review the key SAP concepts and connect each concept to the business process it helps manage.',
    keyTakeaways: [
      'Organizational Units define corporate structure (Company Code, Plant, Storage Location).',
      'Master Data (Vendors, Customers, Materials) is created once and reused repeatedly.',
      'Transactional Data records business operations and updates financial balances automatically.',
    ],
    interactiveElement: {
      type: 'architecture_diagram',
      title: 'Interactive Data Hierarchy Explorer',
    },
  },
  {
    id: 3,
    stepNumber: 3,
    title: 'Understand SAP Business Processes',
    subtitle: 'End-to-End Procure-to-Pay Integration',
    instruction: 'Follow a real-world enterprise procurement flow to observe how Purchase Requisitions flow into Purchase Orders, Goods Receipt, and Invoice Verification.',
    conceptSummary: 'In the Procure-to-Pay process, a purchase order signals vendor commitment. When goods arrive (Goods Receipt), inventory stock increases and financial liabilities update simultaneously without manual reconciliation.',
    hint: 'Follow the course example step by step and identify how the different business activities are connected inside SAP.',
    keyTakeaways: [
      'Document Flow: Purchase Requisition → Purchase Order → Goods Receipt → Invoice Receipt.',
      'Three-way matching guarantees that PO details match physical receipt and supplier invoice.',
      'Every transaction creates immediate ledger entries for full managerial visibility.',
    ],
    interactiveElement: {
      type: 'process_flow',
      title: 'Interactive Procure-to-Pay Workflow Stepper',
    },
  },
  {
    id: 4,
    stepNumber: 4,
    title: 'Review and Complete SAP Fundamentals',
    subtitle: 'Knowledge Synthesis & Practical Takeaways',
    instruction: 'Synthesize the core principles of SAP enterprise computing and verify your understanding through interactive knowledge checkpoints.',
    conceptSummary: 'You have mastered the foundational concepts of SAP enterprise architecture, data segregation, and business process integration. You are ready to apply these concepts in simulated ERP transactions.',
    hint: 'Review the key concepts from the course and make sure you can explain the main ideas before completing SAP Fundamentals.',
    keyTakeaways: [
      'SAP provides enterprise-wide data consistency and unified process governance.',
      'Master Data accuracy is vital for error-free transactional procurement.',
      'Ready to test hands-on skills in the Purchase Order Practice transaction simulator.',
    ],
    interactiveElement: {
      type: 'knowledge_check',
      title: 'Course Checkpoints & Certification Readiness',
    },
  },
];

/* =====================================================================
 * 3. COURSES CATALOGUE
 * ===================================================================== */
export const MOCK_COURSES: Course[] = [
  {
    id: 'sap-fundamentals',
    title: 'SAP Fundamentals',
    category: 'SAP / ERP',
    description: 'Learn the fundamentals of working with an enterprise resource planning system through a guided conceptual journey.',
    duration: '10–15 minutes',
    xp: 250,
    progressPercent: 75,
    subtasksCompleted: 3,
    totalSubtasks: 4,
    isInteractive: true,
    level: 'Beginner',
    overview: 'Learn the fundamentals of working with an enterprise resource planning system through a guided course journey. Understand what SAP is, how ERP integrates business functions, core SAP terminology, and end-to-end business workflows.',
    learningObjectives: [
      'Explain what SAP is and understand its role in enterprise resource planning.',
      'Identify and understand fundamental SAP and ERP concepts.',
      'Understand how SAP supports common business processes and connects business activities.',
      'Review and apply the fundamental concepts learned throughout the course.',
    ],
    interactiveTaskId: 'sap-fundamentals-guide',
  },
  {
    id: 'po-practice',
    title: 'Purchase Order Practice',
    category: 'ERP Operations',
    description: 'Interactive simulation: Create, validate, and submit enterprise purchase orders in a realistic mock software environment.',
    duration: '15 min',
    xp: 250,
    progressPercent: 100,
    subtasksCompleted: 4,
    totalSubtasks: 4,
    isInteractive: true,
    level: 'Beginner',
    overview: 'Hands-on practice task for Transaction ME21N: Select vendor, catalog material, quantity, and dispatch the purchase order.',
    learningObjectives: [
      'Select approved vendors in an enterprise procurement environment.',
      'Specify catalog items and validate procurement quantities.',
      'Review purchase order financial summaries and submit for dispatch.',
    ],
    interactiveTaskId: 'po-practice',
  },
  {
    id: 'erp-fundamentals',
    title: 'ERP Systems Fundamentals',
    category: 'Business Systems',
    description: 'Understand how enterprise resource planning links procurement, inventory, sales, and financial reporting.',
    duration: '30 min',
    xp: 300,
    progressPercent: 100,
    subtasksCompleted: 5,
    totalSubtasks: 5,
    isInteractive: false,
    level: 'Beginner',
    overview: 'Build a practical foundation in connected enterprise resource planning systems.',
    learningObjectives: ['Describe how ERP connects core business functions.'],
  },
  {
    id: 'inventory-management',
    title: 'Inventory & Stock Management',
    category: 'Supply Chain',
    description: 'Learn stock valuation, warehouse transfers, reorder points, and goods receipts processing.',
    duration: '50 min',
    xp: 450,
    progressPercent: 20,
    subtasksCompleted: 1,
    totalSubtasks: 5,
    isInteractive: false,
    level: 'Intermediate',
    overview: 'Learn the core principles behind inventory and stock management.',
    learningObjectives: ['Explain how inventory movements affect stock visibility.'],
  },
  {
    id: 'business-software-essentials',
    title: 'Business Software Essentials',
    category: 'Productivity',
    description: 'Master keyboard shortcuts, data validation, audit trails, and navigation in enterprise workflow suites.',
    duration: '25 min',
    xp: 200,
    progressPercent: 0,
    subtasksCompleted: 0,
    totalSubtasks: 4,
    isInteractive: false,
    level: 'Beginner',
    overview: 'Practice reliable navigation and data handling in business software.',
    learningObjectives: ['Apply validation and audit-aware workflow habits.'],
  },
];

/* =====================================================================
 * 4. SAP FUNDAMENTALS COURSE GUIDE — INDEPENDENT BEHAVIORAL DROP-OFF
 * ===================================================================== */
export const SAP_COURSE_DROPOFFS: StepDropOffStat[] = [
  {
    stepId: 1,
    stepTitle: 'Step 1: Understand SAP Fundamentals',
    usersReached: 150,
    usersCompleted: 138,
    dropOffRatePercent: 8.0,
    avgTimeSeconds: 42,
    wrongClicksAvg: 0.5,
  },
  {
    stepId: 2,
    stepTitle: 'Step 2: Explore Core SAP Concepts',
    usersReached: 138,
    usersCompleted: 116,
    dropOffRatePercent: 16.0,
    avgTimeSeconds: 65,
    wrongClicksAvg: 1.2,
  },
  {
    stepId: 3,
    stepTitle: 'Step 3: Understand SAP Business Processes',
    usersReached: 116,
    usersCompleted: 77,
    dropOffRatePercent: 34.0, // Primary bottleneck in SAP course guide
    avgTimeSeconds: 98,
    wrongClicksAvg: 2.8,
  },
  {
    stepId: 4,
    stepTitle: 'Step 4: Review and Complete',
    usersReached: 77,
    usersCompleted: 72,
    dropOffRatePercent: 7.0,
    avgTimeSeconds: 38,
    wrongClicksAvg: 0.3,
  },
];

/* =====================================================================
 * 5. SAP FUNDAMENTALS COURSE GUIDE — AVERAGE RATINGS PER STEP
 * ===================================================================== */
export const SAP_STEP_RATINGS: StepRatingStat[] = [
  {
    stepId: 1,
    stepTitle: 'Step 1: Understand SAP Fundamentals',
    avgRating: 4.1,
    totalRatings: 32,
  },
  {
    stepId: 2,
    stepTitle: 'Step 2: Explore Core SAP Concepts',
    avgRating: 3.7,
    totalRatings: 28,
  },
  {
    stepId: 3,
    stepTitle: 'Step 3: Understand SAP Business Processes',
    avgRating: 2.4, // Lowest rating correlates with highest drop-off!
    totalRatings: 39,
  },
  {
    stepId: 4,
    stepTitle: 'Step 4: Review and Complete',
    avgRating: 4.5,
    totalRatings: 26,
  },
];

/* =====================================================================
 * 6. SAP FUNDAMENTALS AI THEMES
 * ===================================================================== */
export const SAP_AI_THEMES: AITheme[] = [
  {
    id: 'sap-theme-1',
    title: 'Business process connections lack interactive visual scaffolding',
    commentCount: 16,
    steps: [3],
    summary: 'Learners struggle to grasp how information handoffs occur between purchasing, warehouse, and accounting during the Procure-to-Pay cycle.',
    suggestedAction: 'Add a visual step-by-step document lifecycle diagram highlighting which department owns each document handoff.',
    sentimentBreakdown: { positive: 1, neutral: 2, negative: 13 },
  },
  {
    id: 'sap-theme-2',
    title: 'SAP terminology & acronym overload causes cognitive fatigue',
    commentCount: 10,
    steps: [2],
    summary: 'Multiple learners reported confusion distinguishing between Master Data, Organizational Units, and technical acronyms (PO, GR, IR, CC).',
    suggestedAction: 'Introduce an interactive glossary hover tooltip for enterprise terms in Step 2.',
    sentimentBreakdown: { positive: 1, neutral: 4, negative: 5 },
  },
  {
    id: 'sap-theme-3',
    title: 'ERP conceptual value is clear but needs more real-world examples',
    commentCount: 6,
    steps: [1],
    summary: 'Learners appreciated the overview of ERP benefits, but requested concrete stories showing how small mistakes cascade through databases.',
    suggestedAction: 'Include a 30-second case study snippet of a company preventing duplicate orders using ERP.',
    sentimentBreakdown: { positive: 3, neutral: 2, negative: 1 },
  },
  {
    id: 'sap-theme-4',
    title: 'Synthesis checkpoints and key takeaway pills reinforce learning',
    commentCount: 5,
    steps: [4],
    summary: 'The final review format and key takeaway cards received enthusiastic feedback for solidifying high-level principles.',
    suggestedAction: 'Maintain current checkpoint format and provide a downloadable quick-reference cheat sheet.',
    sentimentBreakdown: { positive: 5, neutral: 0, negative: 0 },
  },
];

/* =====================================================================
 * 7. 8 IDEA CARDS (2 per participant across 4 roles)
 * ===================================================================== */
export const MOCK_IDEA_CARDS: IdeaCard[] = [
  {
    id: 'idea-dev1-a11y',
    participant: 'Developer 1',
    role: 'Full-Stack Developer',
    type: 'accessibility',
    moment: 'Step 3 — Understand SAP Business Processes',
    idea: 'Keyboard-navigable flowchart with ARIA live announcements describing document handoffs when navigating between workflow nodes.',
    howToTest: 'Run a keyboard-only walkthrough with a screen reader comparing task completion time against the visual-only diagram.',
    howToMeasure: 'Measure keyboard completion success rate, task duration, and assistive technology error rates.',
  },
  {
    id: 'idea-dev1-learn',
    participant: 'Developer 1',
    role: 'Full-Stack Developer',
    type: 'learning_experience',
    moment: 'Step 2 — Explore Core SAP Concepts',
    idea: 'Interactive toggle comparing Master Data vs Transactional Data side-by-side with color-coded persistent vs ephemeral badges.',
    howToTest: 'A/B test with 20 cohort learners: Group A receives static text, Group B receives interactive comparison toggle.',
    howToMeasure: 'Compare quiz accuracy on classification questions and time spent on Step 2.',
  },
  {
    id: 'idea-dev2-a11y',
    participant: 'Developer 2',
    role: 'Full-Stack Developer',
    type: 'accessibility',
    moment: 'Step 1 — Understand SAP Fundamentals',
    idea: 'High-contrast text modes and customizable font size toggles for enterprise conceptual cards to assist low-vision learners.',
    howToTest: 'Conduct Lighthouse accessibility audits and gather qualitative feedback from testers using screen magnifiers.',
    howToMeasure: 'Verify WCAG AAA color contrast compliance and measure reading fatigue self-ratings.',
  },
  {
    id: 'idea-dev2-learn',
    participant: 'Developer 2',
    role: 'Full-Stack Developer',
    type: 'learning_experience',
    moment: 'Step 3 — Understand SAP Business Processes',
    idea: 'Micro-simulation showing what happens when a purchase order is submitted without a valid goods receipt (3-way match failure).',
    howToTest: 'Present an intentional error state in the process stepper and ask learners to identify the blocking transaction.',
    howToMeasure: 'Evaluate diagnostic accuracy and reduction in Step 3 drop-off from 34% to under 20%.',
  },
  {
    id: 'idea-ai-a11y',
    participant: 'AI Engineer',
    role: 'AI & Data Specialist',
    type: 'accessibility',
    moment: 'Step 4 — Review and Complete',
    idea: 'Adaptive voice-interactive review assistant using browser speech recognition allowing learners to answer checkpoint questions verbally.',
    howToTest: 'Test voice recognition accuracy across diverse accents (French, English, Arabic) in a quiet vs normal ambient room.',
    howToMeasure: 'Track speech recognition intent match percentage and verbal quiz completion speed.',
  },
  {
    id: 'idea-ai-learn',
    participant: 'AI Engineer',
    role: 'AI & Data Specialist',
    type: 'learning_experience',
    moment: 'Step 2 — Explore Core SAP Concepts',
    idea: 'Contextual AI concept simplifier button ("Explain this concept like I am a business beginner") generating plain-language analogies.',
    howToTest: 'Offer the "Simplify" button on complex terms like "Organizational Units" and measure click-through rates.',
    howToMeasure: 'Compare comprehension scores on terminology questions before and after concept simplification.',
  },
  {
    id: 'idea-mkt-a11y',
    participant: 'Digital Marketer',
    role: 'Product & UX Researcher',
    type: 'accessibility',
    moment: 'Stuck Detection Moments',
    idea: 'Non-modal gentle assistance toast with audible chime and clear visual focus indicator that does not disrupt reading flow.',
    howToTest: 'Measure learner dismissal rate and task abandonment rate when assistance toast appears vs modal takeover.',
    howToMeasure: 'Compare feedback survey response rate (target >75%) and stuck-to-completion recovery rate.',
  },
  {
    id: 'idea-mkt-learn',
    participant: 'Digital Marketer',
    role: 'Product & UX Researcher',
    type: 'learning_experience',
    moment: 'Course Overview & Objectives',
    idea: 'Progressive milestone unlocks: reward learners with digital badges ("ERP Explorer", "Process Navigator") after each step.',
    howToTest: 'Measure course completion rate with gamification badge rewards enabled vs disabled in a 2-day testing trial.',
    howToMeasure: 'Track daily active return rate, overall completion percentage, and streak continuation.',
  },
];

/* =====================================================================
 * 8. SAP FUNDAMENTALS FEEDBACK RECORDS (35 records)
 * ===================================================================== */
export const SAP_FEEDBACK_LIST: FeedbackRecord[] = [
  {
    id: 'sfb-01',
    sessionId: 'sess-sap-101',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 3,
    trigger: 'stuck',
    rating: 2,
    comment: 'The transition from purchase order to goods receipt was hard to follow without seeing who does what.',
    sentiment: 'negative',
    timestamp: '2026-09-23T18:10:00Z',
  },
  {
    id: 'sfb-02',
    sessionId: 'sess-sap-102',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 3,
    trigger: 'stuck',
    rating: 2,
    comment: 'Could not understand how accounting gets updated automatically when warehouse accepts shipment.',
    sentiment: 'negative',
    timestamp: '2026-09-23T18:14:20Z',
  },
  {
    id: 'sfb-03',
    sessionId: 'sess-sap-103',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 3,
    trigger: 'leave',
    rating: 1,
    comment: 'Step 3 had too much business jargon. Felt lost on the three-way match concept.',
    sentiment: 'negative',
    timestamp: '2026-09-23T18:18:00Z',
  },
  {
    id: 'sfb-04',
    sessionId: 'sess-sap-104',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 3,
    trigger: 'stuck',
    rating: 2,
    comment: 'The hint helped, but I still needed a diagram showing the documents moving between teams.',
    sentiment: 'negative',
    timestamp: '2026-09-23T18:22:30Z',
  },
  {
    id: 'sfb-05',
    sessionId: 'sess-sap-105',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 2,
    trigger: 'stuck',
    rating: 3,
    comment: 'Company Code vs Plant vs Storage Location was slightly confusing for a beginner.',
    sentiment: 'neutral',
    timestamp: '2026-09-23T18:25:00Z',
  },
  {
    id: 'sfb-06',
    sessionId: 'sess-sap-106',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 2,
    trigger: 'stuck',
    rating: 2,
    comment: 'So many technical terms! Master data vs transactional data needs a simpler analogy.',
    sentiment: 'negative',
    timestamp: '2026-09-23T18:29:10Z',
  },
  {
    id: 'sfb-07',
    sessionId: 'sess-sap-107',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 1,
    trigger: 'completion',
    rating: 4,
    comment: 'Great explanation of what ERP does! Clear distinction from regular spreadsheet management.',
    sentiment: 'positive',
    timestamp: '2026-09-23T18:32:00Z',
  },
  {
    id: 'sfb-08',
    sessionId: 'sess-sap-108',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 1,
    trigger: 'completion',
    rating: 5,
    comment: 'Loved the overview of SAP German origins and global market share. Very motivating.',
    sentiment: 'positive',
    timestamp: '2026-09-23T18:35:40Z',
  },
  {
    id: 'sfb-09',
    sessionId: 'sess-sap-109',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 4,
    trigger: 'completion',
    rating: 5,
    comment: 'The checkpoint review cards helped me retain all the key points. Ready for the PO practice!',
    sentiment: 'positive',
    timestamp: '2026-09-23T18:40:00Z',
  },
  {
    id: 'sfb-10',
    sessionId: 'sess-sap-110',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 4,
    trigger: 'completion',
    rating: 4,
    comment: 'Summarized everything nicely. Keyboard navigation worked smoothly throughout.',
    sentiment: 'positive',
    timestamp: '2026-09-23T18:43:20Z',
  },
  {
    id: 'sfb-11',
    sessionId: 'sess-sap-111',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 3,
    trigger: 'stuck',
    rating: 2,
    comment: 'I spent 4 minutes on Step 3 trying to understand how the invoice verification connects back to the PO.',
    sentiment: 'negative',
    timestamp: '2026-09-23T18:47:00Z',
  },
  {
    id: 'sfb-12',
    sessionId: 'sess-sap-112',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 3,
    trigger: 'leave',
    rating: 2,
    comment: 'Too dense without a visual roadmap of the workflow.',
    sentiment: 'negative',
    timestamp: '2026-09-23T18:50:15Z',
  },
  {
    id: 'sfb-13',
    sessionId: 'sess-sap-113',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 2,
    trigger: 'completion',
    rating: 4,
    comment: 'Interactive data hierarchy diagram made organizational units much clearer.',
    sentiment: 'positive',
    timestamp: '2026-09-23T18:54:00Z',
  },
  {
    id: 'sfb-14',
    sessionId: 'sess-sap-114',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 1,
    trigger: 'stuck',
    rating: 3,
    comment: 'Needed a concrete business scenario to understand why traditional databases fail.',
    sentiment: 'neutral',
    timestamp: '2026-09-23T18:58:10Z',
  },
  {
    id: 'sfb-15',
    sessionId: 'sess-sap-115',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 3,
    trigger: 'stuck',
    rating: 1,
    comment: 'The difference between Purchase Requisition and Purchase Order was unclear.',
    sentiment: 'negative',
    timestamp: '2026-09-23T19:02:00Z',
  },
  {
    id: 'sfb-16',
    sessionId: 'sess-sap-116',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 3,
    trigger: 'completion',
    rating: 3,
    comment: 'Got it eventually with the hint, but Step 3 is definitely the steepest hill to climb.',
    sentiment: 'neutral',
    timestamp: '2026-09-23T19:05:40Z',
  },
  {
    id: 'sfb-17',
    sessionId: 'sess-sap-117',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 2,
    trigger: 'stuck',
    rating: 2,
    comment: 'More examples of Master Data in everyday life would help beginners.',
    sentiment: 'negative',
    timestamp: '2026-09-23T19:09:00Z',
  },
  {
    id: 'sfb-18',
    sessionId: 'sess-sap-118',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 4,
    trigger: 'completion',
    rating: 5,
    comment: 'Voice commands worked great to navigate between summary checkpoints!',
    sentiment: 'positive',
    timestamp: '2026-09-23T19:12:30Z',
  },
  {
    id: 'sfb-19',
    sessionId: 'sess-sap-119',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 3,
    trigger: 'stuck',
    rating: 2,
    comment: 'The three-way match explanation needs an infographic or animation.',
    sentiment: 'negative',
    timestamp: '2026-09-23T19:16:00Z',
  },
  {
    id: 'sfb-20',
    sessionId: 'sess-sap-120',
    courseId: 'sap-fundamentals',
    taskId: 'sap-fundamentals-guide',
    guideType: 'sap_fundamentals_course',
    stepId: 1,
    trigger: 'completion',
    rating: 4,
    comment: 'Very beginner friendly introduction to enterprise software concepts.',
    sentiment: 'positive',
    timestamp: '2026-09-23T19:20:10Z',
  },
];

/* =====================================================================
 * 9. DASHBOARD INSIGHTS (SAP FUNDAMENTALS ANALYTICS — DEFAULT VIEW)
 * ===================================================================== */
export const MOCK_SAP_DASHBOARD_INSIGHTS: DashboardInsights = {
  kpis: {
    completionRate: 64.2,
    dropOffRate: 35.8,
    feedbackResponseRate: 75.6,
    averageRating: 3.4,
    totalSessions: 150,
    totalFeedback: 38,
  },
  triggerResponseRates: {
    stuck: 72.0,
    leave: 48.0,
    completion: 81.0,
  },
  stepRatings: SAP_STEP_RATINGS,
  stepDropOffs: SAP_COURSE_DROPOFFS,
  aiThemes: SAP_AI_THEMES,
  recommendedFocus: {
    stepId: 3,
    stepTitle: 'Step 3: Understand SAP Business Processes',
    dropOffRatePercent: 34.0,
    negativeCommentsCount: 13,
    aiThemeTitle: 'Business process connections lack interactive visual scaffolding',
    why: [
      'Highest measured drop-off across the SAP Fundamentals course (34.0% of learners stop here)',
      'Lowest average rating (2.4 / 5) across all 4 learning steps',
      '13 out of 16 qualitative comments report disorientation during multi-department document handoffs',
      'AI thematic clustering reveals learners require a visual document lifecycle diagram rather than abstract text',
    ],
    action: 'Implement an interactive Procure-to-Pay document flow diagram with explicit department badges (Purchasing → Warehouse → Accounting).',
  },
  ideaCards: MOCK_IDEA_CARDS,
};

/* =====================================================================
 * 10. PURCHASE ORDER EXISTING MOCK DATA — FULLY PRESERVED
 * ===================================================================== */
export const MOCK_STEP_DROPOFFS: StepDropOffStat[] = [
  {
    stepId: 1,
    stepTitle: 'Step 1: Select Supplier',
    usersReached: 120,
    usersCompleted: 108,
    dropOffRatePercent: 10.0,
    avgTimeSeconds: 24,
    wrongClicksAvg: 0.8,
  },
  {
    stepId: 2,
    stepTitle: 'Step 2: Select Product',
    usersReached: 108,
    usersCompleted: 89,
    dropOffRatePercent: 17.6,
    avgTimeSeconds: 32,
    wrongClicksAvg: 1.4,
  },
  {
    stepId: 3,
    stepTitle: 'Step 3: Enter Quantity',
    usersReached: 89,
    usersCompleted: 58,
    dropOffRatePercent: 34.8,
    avgTimeSeconds: 58,
    wrongClicksAvg: 3.2,
  },
  {
    stepId: 4,
    stepTitle: 'Step 4: Submit PO',
    usersReached: 58,
    usersCompleted: 53,
    dropOffRatePercent: 8.6,
    avgTimeSeconds: 19,
    wrongClicksAvg: 0.4,
  },
];

export const MOCK_AI_THEMES: AITheme[] = [
  {
    id: 'theme-1',
    title: 'Quantity field is unclear & unit of measure unspecified',
    commentCount: 22,
    steps: [3],
    summary: 'Learners struggle to know whether to type boxes, pieces, or batch codes, and many are unsure if zero or decimals are allowed.',
    suggestedAction: 'Clarify Step 3 instructions with an explicit unit example (e.g., "Enter 5 units") and add an inline field hint.',
    sentimentBreakdown: { positive: 1, neutral: 3, negative: 18 },
  },
  {
    id: 'theme-2',
    title: 'Product dropdown options look too similar',
    commentCount: 11,
    steps: [2],
    summary: 'Users report hesitation distinguishing between similar SKU variants in the catalog list without sub-category tags.',
    suggestedAction: 'Add product category tags or SKU codes in the dropdown options for clearer distinction.',
    sentimentBreakdown: { positive: 2, neutral: 4, negative: 5 },
  },
  {
    id: 'theme-3',
    title: 'Vendor lookup search filter missing',
    commentCount: 7,
    steps: [1],
    summary: 'Some users expected a typeahead search rather than scrolling through vendor names.',
    suggestedAction: 'Enable instant filtering in the Supplier select box.',
    sentimentBreakdown: { positive: 2, neutral: 3, negative: 2 },
  },
  {
    id: 'theme-4',
    title: 'Order confirmation prompt gives great clarity',
    commentCount: 5,
    steps: [4],
    summary: 'Learners appreciate the summary table review before the final order dispatch.',
    suggestedAction: 'Maintain current Step 4 summary verification layout as an enterprise best practice.',
    sentimentBreakdown: { positive: 5, neutral: 0, negative: 0 },
  },
];

export const MOCK_FEEDBACK_LIST: FeedbackRecord[] = [
  {
    id: 'fb-01',
    sessionId: 'sess-a101',
    taskId: 'po-practice',
    stepId: 3,
    trigger: 'stuck',
    rating: 1,
    comment: "I didn't know which field I needed to fill or if I should type '10' or '10 boxes'.",
    sentiment: 'negative',
    timestamp: '2026-09-23T14:12:00Z',
  },
  {
    id: 'fb-02',
    sessionId: 'sess-a102',
    taskId: 'po-practice',
    stepId: 3,
    trigger: 'stuck',
    rating: 2,
    comment: 'The input kept rejecting my value because I put pieces instead of plain numbers.',
    sentiment: 'negative',
    timestamp: '2026-09-23T14:15:30Z',
  },
  {
    id: 'fb-03',
    sessionId: 'sess-a103',
    taskId: 'po-practice',
    stepId: 3,
    trigger: 'leave',
    rating: 1,
    comment: 'Got stuck on quantity for 2 minutes without knowing what was wrong, gave up.',
    sentiment: 'negative',
    timestamp: '2026-09-23T14:20:10Z',
  },
  {
    id: 'fb-04',
    sessionId: 'sess-a104',
    taskId: 'po-practice',
    stepId: 3,
    trigger: 'stuck',
    rating: 2,
    comment: 'Instruction just says "Enter Quantity", but not what valid ranges are.',
    sentiment: 'negative',
    timestamp: '2026-09-23T14:22:00Z',
  },
  {
    id: 'fb-05',
    sessionId: 'sess-a105',
    taskId: 'po-practice',
    stepId: 3,
    trigger: 'stuck',
    rating: 1,
    comment: 'Accidentally clicked outside and nothing happened. Needed a hint sooner.',
    sentiment: 'negative',
    timestamp: '2026-09-23T14:25:40Z',
  },
  {
    id: 'fb-06',
    sessionId: 'sess-a106',
    taskId: 'po-practice',
    stepId: 3,
    trigger: 'completion',
    rating: 3,
    comment: 'Managed to complete it once the hint told me to enter an integer > 0.',
    sentiment: 'neutral',
    timestamp: '2026-09-23T14:29:15Z',
  },
];

export const MOCK_DASHBOARD_INSIGHTS: DashboardInsights = {
  kpis: {
    completionRate: 62.5,
    dropOffRate: 37.5,
    feedbackResponseRate: 78.4,
    averageRating: 2.9,
    totalSessions: 120,
    totalFeedback: 32,
  },
  triggerResponseRates: {
    stuck: 72.0,
    leave: 48.0,
    completion: 81.0,
  },
  stepRatings: [
    { stepId: 1, stepTitle: 'Step 1: Select Supplier', avgRating: 4.1, totalRatings: 28 },
    { stepId: 2, stepTitle: 'Step 2: Select Product', avgRating: 3.7, totalRatings: 24 },
    { stepId: 3, stepTitle: 'Step 3: Enter Quantity', avgRating: 2.2, totalRatings: 34 },
    { stepId: 4, stepTitle: 'Step 4: Submit PO', avgRating: 4.6, totalRatings: 22 },
  ],
  stepDropOffs: MOCK_STEP_DROPOFFS,
  aiThemes: MOCK_AI_THEMES,
  recommendedFocus: {
    stepId: 3,
    stepTitle: 'Step 3: Enter Quantity',
    dropOffRatePercent: 34.8,
    negativeCommentsCount: 18,
    aiThemeTitle: 'Quantity field is unclear & unit of measure unspecified',
    why: [
      'Highest measured drop-off across all steps (34.8% of all learners stop here)',
      '18 out of 22 learner comments for this step report negative sentiment',
      'AI theme analysis confirms learners are confused by allowed formats and units',
      'Average time spent is 58s (more than double Step 1 and Step 4)',
    ],
    action: 'Clarify the Step 3 guide instruction by specifying a numeric value and adding an inline placeholder example (e.g. "e.g., 5 units").',
  },
  ideaCards: MOCK_IDEA_CARDS,
};
